// Valid test names for normalization (from legacy Python script)
export const VALID_TEST_NAMES = [
    "Albumin", "Alkalikus foszfatáz (AP)", "Alfa-Amiláz", "Amiláz izoenzimek", "Pankreász specifikus amiláz",
    "Makroamiláz", "Lipáz", "Bilirubin (Összes)", "Bilirubin (Konjugált/Direkt)", "GOT (ASAT)", "GPT (ALAT)",
    "GGT", "LDH", "Kolinészteráz", "Kreatin-kináz (CK)", "CK-MB izoenzim", "Troponin T", "Troponin I",
    "Myoglobin", "BNP", "NT-proBNP", "Karbamid", "Kreatinin", "eGFR", "Húgysav", "Cisztatin C",
    "Glükóz (Vércukor)", "HbA1c", "Fruktózamin", "Inzulin", "C-peptid", "Koleszterin (Összes)",
    "HDL-koleszterin", "LDL-koleszterin", "Triglicerid", "Lipoprotein (a)", "Apolipoprotein A1",
    "Apolipoprotein A2", "Apolipoprotein B", "Lipoprint", "Összfehérje", "Szuperoxid-dizmutáz",
    "Szérum protein elektroforézis (ELFO)", "Immunfixáció", "CRP (C-reaktív protein)", "Prokalcitonin",
    "Amyloid A", "Vas", "TVK (T eljes vaskötő kapacitás)", "Ferritin", "Transzferrin",
    "Szolubilis transzferrin receptor", "Hepszidin", "Nátrium", "Kálium", "Klorid", "Kalcium", "Ionizált kalcium",
    "Magnézium", "Foszfát", "Lítium", "Réz", "Cink", "Szelén", "Jód", "Vérkép (Mennyiségi)", "Vérkép (Minőségi)",
    "Retikulocyta", "Vérsejtsüllyedés", "Prothrombin idő (INR)", "APTI", "Thrombin idő", "Fibrinogén",
    "D-dimer", "Antithrombin III", "Protein C", "Protein S", "APC rezisztencia", "Lupus anticoaguláns",
    "Faktor II", "Faktor V", "Faktor VII", "Faktor VIII", "Faktor IX", "Faktor X", "Faktor XI", "Faktor XII",
    "Faktor XIII", "Anti-Xa", "Von Willebrand antigén", "TSH", "Szabad T4 (fT4)", "Szabad T3 (fT3)", "Anti-TPO",
    "Anti-TG", "TRAK (TSH receptor antitest)", "Thyreoglobulin", "Kalcitonin", "Reverz T3 (rT3)", "LH", "FSH",
    "Ösztradiol", "Progeszteron", "17-OH-Progeszteron", "AMH (Anti-Müllerian hormon)", "Tesztoszteron",
    "Szabad tesztoszteron", "SHBG", "DHEA-S", "Androsztendion", "Dihidro-tesztoszteron", "Béta-hCG", "PAPP-A",
    "Szabad esztriol", "Placentáris növekedési faktor (PlGF)", "Kortizol", "ACTH", "Aldoszteron", "Renin",
    "Prolaktin", "Makroprolaktin", "Növekedési hormon (GH)", "IGF-1", "Adrenalin", "Noradrenalin", "Dopamin",
    "Chromogranin A", "AFP", "CEA", "CA 125", "CA 15-3", "CA 19-9", "CA 72-4", "HE4", "ROMA-index", "PSA",
    "Szabad PSA (fPSA)", "NSE", "S-100 protein", "Béta-2-mikroglobulin", "SCC", "Cyfra 21-1", "TPA",
    "Immunglobulin A (IgA)", "Immunglobulin G (IgG)", "Immunglobulin M (IgM)", "Összes IgE", "Komplement C3",
    "Komplement C4", "CH50", "Reuma faktor (RF)", "Anti-CCP", "ASLO", "ANA (ELISA)", "ANA (Hep-2)", "ENA szűrés",
    "ENA panel (Ro, La, Sm, RNP, Scl-70, Jo-1)", "ds-DNS", "ANCA", "MPO", "PR-3", "Kardiolipin antitest (IgG, IgM)",
    "Béta-2-glikoprotein antitest (IgG, IgM)", "Prothrombin elleni antitest", "Annexin V elleni antitest",
    "tTG IgA", "tTG IgG", "EMA IgA", "EMA IgG", "ASCA (IgA, IgG)", "Aquaporin-4", "Gasztrin-17", "Pepszinogén I",
    "Pepszinogén II", "D-vitamin", "B12-vitamin", "Aktív B12", "Folsav", "A-vitamin", "E-vitamin", "C-vitamin",
    "K-vitamin", "B1-vitamin", "B2-vitamin", "B3-vitamin", "B5-vitamin", "B6-vitamin", "H-vitamin (Biotin)",
    "HIV-1,2", "HBsAg", "Anti-HBs", "Anti-HBc", "Anti-HBc IgM", "HBeAg", "Anti-HBe", "Anti-HCV",
    "Hepatitis A (IgG, IgM)", "Hepatitis E (IgG, IgM)", "Syphilis (Lues)", "CMV (IgG, IgM)", "EBV (IgG, IgM)",
    "HSV 1,2 (IgG, IgM)", "VZV (IgG, IgM)", "Toxoplasma (IgG, IgM)", "Borrelia (IgG, IgM)",
    "Helicobacter pylori IgG", "Chlamydia trachomatis (IgG, IgM, IgA)", "Chlamydia pneumoniae (IgG, IgM, IgA)",
    "Mycoplasma pneumoniae (IgG, IgM, IgA)", "Quantiferon-TB", "SARS-CoV-2 (IgG, IgM)", "Vércsoport",
    "Ellenanyagszűrés", "Leiden mutáció", "Prothrombin (G20210A) mutáció", "MTHFR (C677T, A1298C)",
    "Laktózintolerancia (C/T-13910)", "HLA-B27", "ACE gén", "BRCA1", "BRCA2", "ColonAiQ", "T-lymphocyta",
    "B-lymphocyta", "NK-lymphocyta",
    // Additional common tests
    "Vas (Fe)", "Fehérvérsejtszám", "Vörösvérsejtszám", "Hemoglobin", "Hematokrit", "Trombocitaszám"
];
